language: python

matrix:
  include:
    - sudo: required
      language: python
      python: 3.6
      services:
        - docker
      env: PYPY_BUILD=1

script:
  - docker run -v $PWD:/app quay.io/wenxiang/kafka-cffi-builder
    scripts/build-wheels.sh
  - if [[ ! $(python setup.py --version) =~ dev ]]; then
      echo "Not a dev version, uploading to pypi" &&
      pip install twine &&
      twine upload dist/*.tar.gz wheelhouse/*.whl;
    else
      echo "Dev version, skipping upload";
    fi
