language: python

matrix:
  include:
    - sudo: required
      language: python
      python: 3.6
      services:
        - docker
      env: PYPY_BUILD=1

script:
  - docker run -v $PWD:/app quay.io/wenxiang/kafka-cffi-builder
    scripts/build-wheels.sh
  - pip install twine
  - twine upload wheelhouse/*.whl
